# -*- coding: utf-8 -*-
"""practice22

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L4RWoxP0e220giDkhwjkHWo1JarPAD6a
"""

import streamlit as st
import pandas as pd

#title of the app
st.title('Top Consumption Analysis and YOA Analysis - Insights')

# Add text to the Streamlit app
st.markdown("""
### YOA Analysis

In YOA analysis, the observations are as follows:

- **First year student (only 1 on our list)** is found to have video usage on almost all popular subjects like OBG, ENT, etc. and an ample about of QBanks.
""")


# List of subject titles
subject_titles = ['Dermatology', 'Psychiatry', 'Microbiology', 'Biochemistry']

# Dictionary mapping subjects to average completion time
average_completion_time = {
    'Dermatology': 30,
    'Psychiatry': 25,
    'Microbiology': 35,
    'Biochemistry': 40
}

# Create a dropdown menu
selected_subject = st.selectbox('Select a Subject To Check For Average Pace of Completion', subject_titles)

# Display the selected subject
st.write('You selected:', selected_subject)

# Display the corresponding average completion time
if selected_subject in average_completion_time:
    st.write('Average Completion Time In Days:', average_completion_time[selected_subject])
    st.markdown(f"<p style='font-size: 24px;'>{average_completion_time[selected_subject]}</p>", unsafe_allow_html=True)
else:
    st.write('Average Completion Time: N/A')

# Add text to the left sidebar
st.sidebar.markdown("""
    Majority users have a spike starting from April, and Aug - November highest usage
    Most of them are doctors
    Heavy usage in the second half of the year
    Extreme consistency maintained
""")


import streamlit as st
import pandas as pd

# Sample data
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
video_counts = [422, 5839, 1234, 5678, 9876, 5432, 8765, 4321, 9876, 1234, 5678, 9876]

# Create a dictionary to store the data
data = {'Month': months, 'Video Count': video_counts}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Sort the DataFrame by the 'Month' column
df_sorted = df.sort_values(by='Month')

# Plot a bar chart
import matplotlib.pyplot as plt

# Sorting the DataFrame just in case it's not sorted
df_sorted = df.sort_values(by='Month')

# Creating a bar chart using Matplotlib
plt.figure(figsize=(10, 6))  # Adjust the figure size as needed
plt.bar(df_sorted['Month'], df_sorted['Video Count'], color='blue')  # You can customize the color
plt.title('Distinct Count of Video Titles by Month')
plt.xlabel('Month')
plt.ylabel('Video Count')
plt.xticks(rotation=45)  # Rotate labels to make them readable
st.pyplot(plt)




import streamlit as st
import matplotlib.pyplot as plt
import streamlit as st

# Add text to the sidebar
st.sidebar.markdown("""
<div style="display: flex; flex-wrap: wrap;">
  <div style="width: 53.33%; padding: 10px;">
    <div style="border: 1px solid #ccc; padding: 10px;">
      <p>Majority users have a spike starting from April, and Aug - November highest usage</p>
      <p>💡Most of them are doctors</p>
      <p>💡Heavy usage in the second half of the year</p>
      <p>💡Extreme consistency maintained</p>
    </div>
  </div>
  <div style="width: 53.33%; padding: 10px;">
    <div style="border: 1px solid #ccc; padding: 10px;">
      <p>The students usually study from tier 1 colleges</p>
      <p>First years - 6am - 9 am and 2pm to 6 pm</p>
      <p>Second years -</p>
      <p>They study for an average of 5 hours per day</p>
    </div>
  </div>
  <div style="width: 53.33%; padding: 10px;">
    <div style="border: 1px solid #ccc; padding: 10px;">
      <p>The ratio for video watch and qbanks is 1:4. That is, for every 4 videos watched, 1 qbank is solved.</p>
      <p>The time gap between creating an account and buying the plan is 1 year constant throughout majority users.</p>
      <p>Higher videos does not always mean high qbank usage and notes usage.</p>
    </div>
  </div>
</div>
""", unsafe_allow_html=True)



# Sample data
labels = ['QBank Usage', 'Notes', 'Video Usage', 'Others']
sizes = [14, 34, 42, 10]
colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99']

# Create a pie chart with a smaller size
fig1, ax1 = plt.subplots(figsize=(6, 6))  # You've set the figure size here
ax1.pie(sizes, colors=colors, labels=labels, autopct='%1.1f%%', startangle=90)
ax1.axis('equal')  # Ensures the pie chart is a circle

#Display the pie chart
st.pyplot(fig1)

# Add text to the right side of the Streamlit app
st.markdown("""
<div style="float: right; width: 50%;">
  <p>The following statistics has been obtained by taking the average of the count of each unique event present in the API logs for each user. An average of all the user's data has been displayed here.</p>
</div>
""", unsafe_allow_html=True)


import pandas as pd

# Sample data
data4 = {
    'Subject Name': ['Anaesthesia', 'Anatomy', 'Biochemistry', 'Cardiology', 'Community Medicine', 'COVID-19 Updates', 'Delta MCQ Discussion', 'Delta Recent Updates', 'Delta: MCQ Discussion videos', 'Dermatology', 'E6 MCQ Discussion', 'E6 Revision Videos', 'E6.5 Revision Videos', 'Endocrinology', 'ENT', 'Forensic Medicine', 'Gastroenterology', 'Gastrointestinal System', 'Haematology', 'Integrated Sessions', 'Marrow Live +', 'Marrow Revision Videos', 'Medicine', 'Microbiology', 'Nephrology', 'Neurology', 'Obstetrics & Gynaecology', 'Ophthalmology', 'Orthopaedics', 'Paediatrics', 'Pathology', 'Pharmacology', 'Physiology', 'Psychiatry', 'Pulmonology', 'Radiology', 'Rheumatology & Immunology', 'Surgery'],
    'Average Time Taken to Finish the Subject': [21.5, 71.1, 45.9, 16.2, 78.6, 5, 19, 7.6, 8.6, 22.7, 20.8, 32.3, 65.5, 14.8, 46.8, 27.0, 10.75, 1, 13.5, 2, 1, 27.6, 166.9, 57.7, 15.5, 8, 79.5, 29.4, 20.8, 42.0, 56.1, 56.2, 45.2, 13.48, 14.5, 29.9375, 9.875, 58.0]
}

# Create a DataFrame
df4 = pd.DataFrame(data4)

# Display the title as a markdown string
st.markdown("### Average time taken by a student to finish a subject from a pool of high consumption users")

# Display the DataFrame as a table
st.table(df4)


# Display the title as a markdown string
st.markdown("### Questions Under Hypothesis Answered Below")

import streamlit as st

# Create an expander for Question 1
with st.expander("Question 1: Is there a significant difference between the top completion users and normal users"):
    st.markdown("""
    Answer: There is a significant difference between a normal user and a top consumer. A normal user will complete the subjects without a pattern, but a top consumer finishes the subjects in a stretch. (refer to the table for avg days a subject takes to finish). Find the graph below.
    """)

# Create an expander for Question 2
with st.expander("Question 2: Majority of the top completion users are not from the same college"):
    st.markdown("""
    Answer: Most of the users belong to tier 1 medical colleges and also government medical colleges. Here is a list of top 4: Karnataka Institute of Medical Sciences, Hubballi All India Institute of Medical Sciences, Bhubaneswar Armed Forces Medical College, Pune Assam Medial College, Dibrugarh Belagavi Institute of Medical Sciences, Belagavi Bukovinian State Medical University Chamrajanagar Institute of Medical Sciences, Karnataka Dr. Rajendar Prasad Government Medical College, Tanda, H.P Government Dharmapuri Medical College, Dharmapuri Government Medical College, Kota Government Medical College, Kozhikode, Calicut Government Thiruvannamalai Medical College, Thiruvannamalai K A P Viswanathan Government Medical College, Trichy Mahatma Gandhi Medical College & Research Institute Nilratan Sircar Medical College, Kolkata Seth GS Medical College, Mumbai T S Misra Medical College & Hospital, Amusi, Lucknow
    """)

# Create an expander for Question 3
with st.expander("Question 3: Do top completion users did not finish the subjects in sequence?"):
    st.markdown("""
    Answer: Top consumption users finish the subject in a sequence and in a span of 2-3 months.
    """)




# Display the title as a markdown string
st.markdown("### Conclusion")